from .general import SYMPTOMS_GENERAL, RULES_GENERAL
from .brakes import SYMPTOMS_BRAKES, RULES_BRAKES
from .cooling import SYMPTOMS_COOLING, RULES_COOLING
from .wheels import SYMPTOMS_WHEELS, RULES_WHEELS
from .engine_fuel import SYMPTOMS_ENGINE_FUEL, RULES_ENGINE_FUEL
from .engine_ignition import SYMPTOMS_ENGINE_IGNITION, RULES_ENGINE_IGNITION
from .engine_mechanical import SYMPTOMS_ENGINE_MECHANICAL, RULES_ENGINE_MECHANICAL
from .steering_suspension import SYMPTOMS_STEERING_SUSPENSION, RULES_STEERING_SUSPENSION
from .transmission import SYMPTOMS_TRANSMISSION, RULES_TRANSMISSION
from .electrical_lighting import SYMPTOMS_ELECTRICAL_LIGHTING, RULES_ELECTRICAL_LIGHTING
from .climate_ac import SYMPTOMS_CLIMATE_AC, RULES_CLIMATE_AC

SYMPTOMS = (
    SYMPTOMS_GENERAL
    + SYMPTOMS_BRAKES
    + SYMPTOMS_COOLING
    + SYMPTOMS_WHEELS
    + SYMPTOMS_ENGINE_FUEL
    + SYMPTOMS_ENGINE_IGNITION
    + SYMPTOMS_ENGINE_MECHANICAL
    + SYMPTOMS_STEERING_SUSPENSION
    + SYMPTOMS_TRANSMISSION
    + SYMPTOMS_ELECTRICAL_LIGHTING
    + SYMPTOMS_CLIMATE_AC
)

RULES = (
    RULES_GENERAL
    + RULES_BRAKES
    + RULES_COOLING
    + RULES_WHEELS
    + RULES_ENGINE_FUEL
    + RULES_ENGINE_IGNITION
    + RULES_ENGINE_MECHANICAL
    + RULES_STEERING_SUSPENSION
    + RULES_TRANSMISSION
    + RULES_ELECTRICAL_LIGHTING
    + RULES_CLIMATE_AC
)
